[workspace]

members = [
    "game",             # Main Binary
    "common_lib",       # Common Library
    "core_lib",         # Core Library
    "gameplay_lib",     # Gameplay Library
]
resolver = "2"

[workspace.dependencies]
env_logger = "0.11.5"
log = "0.4.22"